sudo: required
dist: trusty
language: java

matrix:
  include:
  - jdk: oraclejdk7
    env: BUILD=GRADLE

  - jdk: oraclejdk8
    env: BUILD=BAZEL

  - jdk: oraclejdk8
    env: BUILD=GRADLE

before_install:
  - case "$BUILD" in
      "BAZEL")
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list ;
        curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add - ;
        sudo apt-get update ;;
      "GRADLE")
        mkdir -p $HOME/.gradle ;
        cat gradle/errorprone/warnings > $HOME/.gradle/gradle.properties ;
        cat gradle/errorprone/experimental_errors >> $HOME/.gradle/gradle.properties ;
        cat gradle/errorprone/experimental_warnings  >> $HOME/.gradle/gradle.properties ;;
    esac

install:
  - case "$BUILD" in
      "BAZEL")
        sudo apt-get install bazel ;
        bazel version;;
    esac

# TODO(sebright) Turn on the deprecation warning after we upgrade to truth 0.31.
# It undeprecates DoubleSubject.isEqualTo(Double).

# TODO(sebright) Find a way to disable the "cast" warning only for Protocol Buffer generated code.

# TODO(bdrutu): Find a way to enable try. We use try-with-resources without
# using the local variable.

# TODO(bdrutu): rawtypes, serial and unchecked are removed because
# com_google_protobuf_java. Re-enable them when the issue gets fixed.

# We skip building the tests with Java 6, because they use try-with-resources.
script:
  - case "$BUILD" in
      "BAZEL")
        bazel test ... --javacopt=-Werror --javacopt=-Xlint:all --javacopt=-Xlint:-cast --javacopt=-Xlint:-deprecation --javacopt=-Xlint:-try --javacopt=-Xlint:-rawtypes --javacopt=-Xlint:-serial --javacopt=-Xlint:-unchecked --config=error_prone_warnings --config=error_prone_experimental_warnings ;;
      "GRADLE")
        ./gradlew clean assemble --stacktrace ;
        case "$TRAVIS_JDK_VERSION" in
          "oraclejdk8")
            ./gradlew check :instrumentation-java-all:jacocoTestReport ;;
          "oraclejdk7")
            ./gradlew check ;;
          "openjdk6")
            ./gradlew check ;;
          *)
            echo "Missing case $TRAVIS_JDK_VERSION" ;
            exit 1 ;;
        esac
    esac

after_success:
  - if \[ "$BUILD" = "GRADLE" \] &&  \[ "$TRAVIS_JDK_VERSION" == "oraclejdk8" \]; then
    ./gradlew :instrumentation-java-all:coveralls --stacktrace ;
    bash <(curl -s https://codecov.io/bash) ;
    fi

before_cache:
  - rm -fr $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
